#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

dunst &

bspc monitor -d "1: Discord" "2: Terminal" "3: Music" "4: Browser" 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^4' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty dektop='^2'

setxkbmap sv &
$HOME/.screenlayout/display.sh
feh --bg-fill ~/Pictures/currentWallpaper.png
xsetroot -cursor_name left_ptr
picom -f &
